/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QVBoxLayout *verticalLayout;
    QTabWidget *tabWidget;
    QWidget *tab;
    QLineEdit *firstNameEdit;
    QLabel *label;
    QLabel *label_2;
    QSpinBox *ageSpinBox;
    QLineEdit *playerNameEdit;
    QLabel *label_3;
    QLabel *label_4;
    QLineEdit *occupationEdit;
    QLineEdit *residenceEdit;
    QLineEdit *birthplaceEdit;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QSpinBox *strSpinbox;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QSpinBox *dexSpinbox;
    QSpinBox *intSpinbox;
    QSpinBox *conSpinbox;
    QSpinBox *appSpinbox;
    QSpinBox *powSpinbox;
    QSpinBox *sizSpinbox;
    QSpinBox *eduSpinbox;
    QLabel *label_15;
    QSpinBox *hpSpinbox;
    QSpinBox *sanitySpinbox;
    QLabel *label_16;
    QLabel *label_17;
    QSpinBox *mpSpinbox;
    QPushButton *pushButton;
    QLabel *label_18;
    QSpinBox *luckSpinbox;
    QCheckBox *checkBox;
    QLabel *label_19;
    QSpinBox *buildSpinbox;
    QLabel *label_20;
    QLabel *dmgBonusLab;
    QWidget *tab_2;
    QSpinBox *acctSpinner;
    QSpinBox *anthroSpinner;
    QSpinBox *appraiseSpinner;
    QSpinBox *archaeologySpinner;
    QSpinBox *artSpinner;
    QSpinBox *charmSpinner;
    QSpinBox *climbSpinner;
    QSpinBox *creditRateSpinner;
    QSpinBox *cthulhuMythosSpinner;
    QSpinBox *disguiseSpinner;
    QSpinBox *dodgeSpinner;
    QSpinBox *driveSpinner;
    QSpinBox *elecRepairSpinner;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QSpinBox *fastTalkSpinner;
    QSpinBox *historySpinner;
    QLabel *label_48;
    QSpinBox *intimidateSpinner;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QSpinBox *lawSpinner;
    QSpinBox *firstAidSpinner;
    QLabel *label_52;
    QLabel *label_53;
    QSpinBox *librarySpinner;
    QLabel *label_54;
    QLabel *label_55;
    QSpinBox *listenSpinner;
    QSpinBox *jumpSpinner;
    QSpinBox *langOtherSpinner;
    QSpinBox *brawlSpinner;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QSpinBox *handgunSpinner;
    QSpinBox *rifleSpinner;
    QSpinBox *langOwnSpinner;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QSpinBox *navSpinner;
    QSpinBox *rideSpinner;
    QLabel *label_62;
    QSpinBox *lockSpinner;
    QLabel *label_63;
    QLabel *label_64;
    QLabel *label_65;
    QLabel *label_66;
    QLabel *label_67;
    QSpinBox *scienceSpinner;
    QSpinBox *pilotSpinner;
    QLabel *label_68;
    QSpinBox *psySpinner;
    QSpinBox *occultSpinner;
    QLabel *label_69;
    QSpinBox *hvMacSpinner;
    QLabel *label_70;
    QLabel *label_71;
    QLabel *label_72;
    QSpinBox *persuadeSpinner;
    QSpinBox *medSpinner;
    QLabel *label_73;
    QSpinBox *psychanalySpinner;
    QSpinBox *mRepairSpinner;
    QSpinBox *naturalSpinner;
    QSpinBox *swimSpinner;
    QSpinBox *sleightSpinner;
    QLabel *label_76;
    QLabel *label_78;
    QLabel *label_80;
    QLabel *label_81;
    QSpinBox *throwSpinner;
    QLabel *label_83;
    QLabel *label_85;
    QSpinBox *stealthSpinner;
    QSpinBox *spotSpinner;
    QSpinBox *survivalSpinner;
    QLabel *label_86;
    QSpinBox *trackSpinner;
    QWidget *tab_3;
    QLabel *descLab;
    QLabel *descLab_2;
    QLabel *descLab_3;
    QLabel *descLab_4;
    QLabel *descLab_5;
    QLabel *descLab_6;
    QLabel *descLab_7;
    QLabel *descLab_8;
    QLabel *descLab_10;
    QLabel *descLab_11;
    QLabel *descLab_12;
    QTextEdit *descEdit;
    QTextEdit *beliefEdit;
    QTextEdit *sigPplEdit;
    QTextEdit *locEdit;
    QTextEdit *possEdit;
    QTextEdit *traitEdit;
    QTextEdit *injEdit;
    QTextEdit *fearEdit;
    QTextEdit *spellEdit;
    QTextEdit *encounterEdit;
    QTextEdit *gearEdit;
    QWidget *tab_4;
    QVBoxLayout *verticalLayout_2;
    QTextEdit *notesEdit;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(752, 675);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        verticalLayout = new QVBoxLayout(centralWidget);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        firstNameEdit = new QLineEdit(tab);
        firstNameEdit->setObjectName(QStringLiteral("firstNameEdit"));
        firstNameEdit->setGeometry(QRect(20, 80, 113, 22));
        label = new QLabel(tab);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 60, 59, 14));
        label_2 = new QLabel(tab);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 110, 31, 16));
        ageSpinBox = new QSpinBox(tab);
        ageSpinBox->setObjectName(QStringLiteral("ageSpinBox"));
        ageSpinBox->setGeometry(QRect(60, 110, 47, 23));
        playerNameEdit = new QLineEdit(tab);
        playerNameEdit->setObjectName(QStringLiteral("playerNameEdit"));
        playerNameEdit->setGeometry(QRect(20, 30, 113, 22));
        label_3 = new QLabel(tab);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(20, 10, 59, 14));
        label_4 = new QLabel(tab);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(20, 140, 71, 16));
        occupationEdit = new QLineEdit(tab);
        occupationEdit->setObjectName(QStringLiteral("occupationEdit"));
        occupationEdit->setGeometry(QRect(20, 160, 113, 22));
        residenceEdit = new QLineEdit(tab);
        residenceEdit->setObjectName(QStringLiteral("residenceEdit"));
        residenceEdit->setGeometry(QRect(20, 210, 113, 22));
        birthplaceEdit = new QLineEdit(tab);
        birthplaceEdit->setObjectName(QStringLiteral("birthplaceEdit"));
        birthplaceEdit->setGeometry(QRect(20, 260, 113, 22));
        label_5 = new QLabel(tab);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 190, 71, 16));
        label_6 = new QLabel(tab);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(20, 240, 71, 16));
        label_7 = new QLabel(tab);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(250, 10, 31, 16));
        strSpinbox = new QSpinBox(tab);
        strSpinbox->setObjectName(QStringLiteral("strSpinbox"));
        strSpinbox->setGeometry(QRect(250, 30, 47, 23));
        label_8 = new QLabel(tab);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(310, 10, 31, 16));
        label_9 = new QLabel(tab);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(370, 10, 31, 16));
        label_10 = new QLabel(tab);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(250, 60, 31, 16));
        label_11 = new QLabel(tab);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(310, 60, 31, 16));
        label_12 = new QLabel(tab);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(370, 60, 31, 16));
        label_13 = new QLabel(tab);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(250, 110, 31, 16));
        label_14 = new QLabel(tab);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(310, 110, 31, 16));
        dexSpinbox = new QSpinBox(tab);
        dexSpinbox->setObjectName(QStringLiteral("dexSpinbox"));
        dexSpinbox->setGeometry(QRect(310, 30, 47, 23));
        intSpinbox = new QSpinBox(tab);
        intSpinbox->setObjectName(QStringLiteral("intSpinbox"));
        intSpinbox->setGeometry(QRect(370, 30, 47, 23));
        conSpinbox = new QSpinBox(tab);
        conSpinbox->setObjectName(QStringLiteral("conSpinbox"));
        conSpinbox->setGeometry(QRect(250, 80, 47, 23));
        appSpinbox = new QSpinBox(tab);
        appSpinbox->setObjectName(QStringLiteral("appSpinbox"));
        appSpinbox->setGeometry(QRect(300, 80, 47, 23));
        powSpinbox = new QSpinBox(tab);
        powSpinbox->setObjectName(QStringLiteral("powSpinbox"));
        powSpinbox->setGeometry(QRect(360, 80, 47, 23));
        sizSpinbox = new QSpinBox(tab);
        sizSpinbox->setObjectName(QStringLiteral("sizSpinbox"));
        sizSpinbox->setGeometry(QRect(250, 130, 47, 23));
        eduSpinbox = new QSpinBox(tab);
        eduSpinbox->setObjectName(QStringLiteral("eduSpinbox"));
        eduSpinbox->setGeometry(QRect(310, 130, 47, 23));
        label_15 = new QLabel(tab);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(250, 180, 31, 16));
        hpSpinbox = new QSpinBox(tab);
        hpSpinbox->setObjectName(QStringLiteral("hpSpinbox"));
        hpSpinbox->setGeometry(QRect(250, 200, 47, 23));
        sanitySpinbox = new QSpinBox(tab);
        sanitySpinbox->setObjectName(QStringLiteral("sanitySpinbox"));
        sanitySpinbox->setGeometry(QRect(310, 200, 47, 23));
        label_16 = new QLabel(tab);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(310, 180, 41, 16));
        label_17 = new QLabel(tab);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(380, 180, 81, 16));
        mpSpinbox = new QSpinBox(tab);
        mpSpinbox->setObjectName(QStringLiteral("mpSpinbox"));
        mpSpinbox->setGeometry(QRect(380, 200, 47, 23));
        pushButton = new QPushButton(tab);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(560, 30, 131, 22));
        label_18 = new QLabel(tab);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(380, 260, 31, 16));
        luckSpinbox = new QSpinBox(tab);
        luckSpinbox->setObjectName(QStringLiteral("luckSpinbox"));
        luckSpinbox->setGeometry(QRect(380, 280, 47, 23));
        checkBox = new QCheckBox(tab);
        checkBox->setObjectName(QStringLiteral("checkBox"));
        checkBox->setGeometry(QRect(250, 230, 101, 20));
        label_19 = new QLabel(tab);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(250, 260, 31, 16));
        buildSpinbox = new QSpinBox(tab);
        buildSpinbox->setObjectName(QStringLiteral("buildSpinbox"));
        buildSpinbox->setGeometry(QRect(250, 280, 47, 23));
        label_20 = new QLabel(tab);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(250, 310, 91, 16));
        dmgBonusLab = new QLabel(tab);
        dmgBonusLab->setObjectName(QStringLiteral("dmgBonusLab"));
        dmgBonusLab->setGeometry(QRect(250, 330, 41, 16));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        acctSpinner = new QSpinBox(tab_2);
        acctSpinner->setObjectName(QStringLiteral("acctSpinner"));
        acctSpinner->setGeometry(QRect(110, 20, 47, 23));
        anthroSpinner = new QSpinBox(tab_2);
        anthroSpinner->setObjectName(QStringLiteral("anthroSpinner"));
        anthroSpinner->setGeometry(QRect(110, 50, 47, 23));
        appraiseSpinner = new QSpinBox(tab_2);
        appraiseSpinner->setObjectName(QStringLiteral("appraiseSpinner"));
        appraiseSpinner->setGeometry(QRect(110, 80, 47, 23));
        archaeologySpinner = new QSpinBox(tab_2);
        archaeologySpinner->setObjectName(QStringLiteral("archaeologySpinner"));
        archaeologySpinner->setGeometry(QRect(110, 110, 47, 23));
        artSpinner = new QSpinBox(tab_2);
        artSpinner->setObjectName(QStringLiteral("artSpinner"));
        artSpinner->setGeometry(QRect(110, 140, 47, 23));
        charmSpinner = new QSpinBox(tab_2);
        charmSpinner->setObjectName(QStringLiteral("charmSpinner"));
        charmSpinner->setGeometry(QRect(110, 170, 47, 23));
        climbSpinner = new QSpinBox(tab_2);
        climbSpinner->setObjectName(QStringLiteral("climbSpinner"));
        climbSpinner->setGeometry(QRect(110, 200, 47, 23));
        creditRateSpinner = new QSpinBox(tab_2);
        creditRateSpinner->setObjectName(QStringLiteral("creditRateSpinner"));
        creditRateSpinner->setGeometry(QRect(110, 230, 47, 23));
        cthulhuMythosSpinner = new QSpinBox(tab_2);
        cthulhuMythosSpinner->setObjectName(QStringLiteral("cthulhuMythosSpinner"));
        cthulhuMythosSpinner->setGeometry(QRect(110, 260, 47, 23));
        disguiseSpinner = new QSpinBox(tab_2);
        disguiseSpinner->setObjectName(QStringLiteral("disguiseSpinner"));
        disguiseSpinner->setGeometry(QRect(110, 290, 47, 23));
        dodgeSpinner = new QSpinBox(tab_2);
        dodgeSpinner->setObjectName(QStringLiteral("dodgeSpinner"));
        dodgeSpinner->setGeometry(QRect(110, 320, 47, 23));
        driveSpinner = new QSpinBox(tab_2);
        driveSpinner->setObjectName(QStringLiteral("driveSpinner"));
        driveSpinner->setGeometry(QRect(110, 350, 47, 23));
        elecRepairSpinner = new QSpinBox(tab_2);
        elecRepairSpinner->setObjectName(QStringLiteral("elecRepairSpinner"));
        elecRepairSpinner->setGeometry(QRect(110, 380, 47, 23));
        label_35 = new QLabel(tab_2);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(0, 20, 71, 16));
        label_36 = new QLabel(tab_2);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(0, 50, 81, 16));
        label_37 = new QLabel(tab_2);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(0, 110, 81, 16));
        label_38 = new QLabel(tab_2);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(0, 140, 81, 16));
        label_39 = new QLabel(tab_2);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(0, 170, 81, 16));
        label_40 = new QLabel(tab_2);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(0, 200, 81, 16));
        label_41 = new QLabel(tab_2);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(0, 230, 81, 16));
        label_42 = new QLabel(tab_2);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(0, 260, 81, 16));
        label_43 = new QLabel(tab_2);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(0, 290, 81, 16));
        label_44 = new QLabel(tab_2);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(0, 320, 81, 16));
        label_45 = new QLabel(tab_2);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(0, 350, 81, 16));
        label_46 = new QLabel(tab_2);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(0, 380, 81, 16));
        label_47 = new QLabel(tab_2);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(0, 80, 81, 16));
        fastTalkSpinner = new QSpinBox(tab_2);
        fastTalkSpinner->setObjectName(QStringLiteral("fastTalkSpinner"));
        fastTalkSpinner->setGeometry(QRect(280, 20, 47, 23));
        historySpinner = new QSpinBox(tab_2);
        historySpinner->setObjectName(QStringLiteral("historySpinner"));
        historySpinner->setGeometry(QRect(280, 170, 47, 23));
        label_48 = new QLabel(tab_2);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(170, 50, 81, 16));
        intimidateSpinner = new QSpinBox(tab_2);
        intimidateSpinner->setObjectName(QStringLiteral("intimidateSpinner"));
        intimidateSpinner->setGeometry(QRect(280, 200, 47, 23));
        label_49 = new QLabel(tab_2);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(170, 260, 111, 16));
        label_50 = new QLabel(tab_2);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(170, 80, 81, 16));
        label_51 = new QLabel(tab_2);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(170, 110, 81, 16));
        lawSpinner = new QSpinBox(tab_2);
        lawSpinner->setObjectName(QStringLiteral("lawSpinner"));
        lawSpinner->setGeometry(QRect(280, 320, 47, 23));
        firstAidSpinner = new QSpinBox(tab_2);
        firstAidSpinner->setObjectName(QStringLiteral("firstAidSpinner"));
        firstAidSpinner->setGeometry(QRect(280, 140, 47, 23));
        label_52 = new QLabel(tab_2);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(170, 230, 81, 16));
        label_53 = new QLabel(tab_2);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(170, 20, 71, 16));
        librarySpinner = new QSpinBox(tab_2);
        librarySpinner->setObjectName(QStringLiteral("librarySpinner"));
        librarySpinner->setGeometry(QRect(280, 350, 47, 23));
        label_54 = new QLabel(tab_2);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(170, 170, 81, 16));
        label_55 = new QLabel(tab_2);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(170, 380, 81, 16));
        listenSpinner = new QSpinBox(tab_2);
        listenSpinner->setObjectName(QStringLiteral("listenSpinner"));
        listenSpinner->setGeometry(QRect(280, 380, 47, 23));
        jumpSpinner = new QSpinBox(tab_2);
        jumpSpinner->setObjectName(QStringLiteral("jumpSpinner"));
        jumpSpinner->setGeometry(QRect(280, 230, 47, 23));
        langOtherSpinner = new QSpinBox(tab_2);
        langOtherSpinner->setObjectName(QStringLiteral("langOtherSpinner"));
        langOtherSpinner->setGeometry(QRect(280, 260, 47, 23));
        brawlSpinner = new QSpinBox(tab_2);
        brawlSpinner->setObjectName(QStringLiteral("brawlSpinner"));
        brawlSpinner->setGeometry(QRect(280, 50, 47, 23));
        label_56 = new QLabel(tab_2);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(170, 200, 81, 16));
        label_57 = new QLabel(tab_2);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(170, 290, 101, 16));
        label_58 = new QLabel(tab_2);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(170, 140, 81, 16));
        handgunSpinner = new QSpinBox(tab_2);
        handgunSpinner->setObjectName(QStringLiteral("handgunSpinner"));
        handgunSpinner->setGeometry(QRect(280, 80, 47, 23));
        rifleSpinner = new QSpinBox(tab_2);
        rifleSpinner->setObjectName(QStringLiteral("rifleSpinner"));
        rifleSpinner->setGeometry(QRect(280, 110, 47, 23));
        langOwnSpinner = new QSpinBox(tab_2);
        langOwnSpinner->setObjectName(QStringLiteral("langOwnSpinner"));
        langOwnSpinner->setGeometry(QRect(280, 290, 47, 23));
        label_59 = new QLabel(tab_2);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(170, 350, 81, 16));
        label_60 = new QLabel(tab_2);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(170, 320, 81, 16));
        label_61 = new QLabel(tab_2);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(360, 380, 81, 16));
        navSpinner = new QSpinBox(tab_2);
        navSpinner->setObjectName(QStringLiteral("navSpinner"));
        navSpinner->setGeometry(QRect(470, 140, 47, 23));
        rideSpinner = new QSpinBox(tab_2);
        rideSpinner->setObjectName(QStringLiteral("rideSpinner"));
        rideSpinner->setGeometry(QRect(470, 350, 47, 23));
        label_62 = new QLabel(tab_2);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(360, 320, 101, 16));
        lockSpinner = new QSpinBox(tab_2);
        lockSpinner->setObjectName(QStringLiteral("lockSpinner"));
        lockSpinner->setGeometry(QRect(470, 20, 47, 23));
        label_63 = new QLabel(tab_2);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(360, 80, 81, 16));
        label_64 = new QLabel(tab_2);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(360, 260, 111, 16));
        label_65 = new QLabel(tab_2);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(360, 50, 81, 16));
        label_66 = new QLabel(tab_2);
        label_66->setObjectName(QStringLiteral("label_66"));
        label_66->setGeometry(QRect(360, 230, 81, 16));
        label_67 = new QLabel(tab_2);
        label_67->setObjectName(QStringLiteral("label_67"));
        label_67->setGeometry(QRect(360, 20, 71, 16));
        scienceSpinner = new QSpinBox(tab_2);
        scienceSpinner->setObjectName(QStringLiteral("scienceSpinner"));
        scienceSpinner->setGeometry(QRect(470, 380, 47, 23));
        pilotSpinner = new QSpinBox(tab_2);
        pilotSpinner->setObjectName(QStringLiteral("pilotSpinner"));
        pilotSpinner->setGeometry(QRect(470, 260, 47, 23));
        label_68 = new QLabel(tab_2);
        label_68->setObjectName(QStringLiteral("label_68"));
        label_68->setGeometry(QRect(360, 140, 81, 16));
        psySpinner = new QSpinBox(tab_2);
        psySpinner->setObjectName(QStringLiteral("psySpinner"));
        psySpinner->setGeometry(QRect(470, 290, 47, 23));
        occultSpinner = new QSpinBox(tab_2);
        occultSpinner->setObjectName(QStringLiteral("occultSpinner"));
        occultSpinner->setGeometry(QRect(470, 170, 47, 23));
        label_69 = new QLabel(tab_2);
        label_69->setObjectName(QStringLiteral("label_69"));
        label_69->setGeometry(QRect(360, 200, 101, 16));
        hvMacSpinner = new QSpinBox(tab_2);
        hvMacSpinner->setObjectName(QStringLiteral("hvMacSpinner"));
        hvMacSpinner->setGeometry(QRect(470, 200, 47, 23));
        label_70 = new QLabel(tab_2);
        label_70->setObjectName(QStringLiteral("label_70"));
        label_70->setGeometry(QRect(360, 110, 81, 16));
        label_71 = new QLabel(tab_2);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(360, 350, 81, 16));
        label_72 = new QLabel(tab_2);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(360, 170, 81, 16));
        persuadeSpinner = new QSpinBox(tab_2);
        persuadeSpinner->setObjectName(QStringLiteral("persuadeSpinner"));
        persuadeSpinner->setGeometry(QRect(470, 230, 47, 23));
        medSpinner = new QSpinBox(tab_2);
        medSpinner->setObjectName(QStringLiteral("medSpinner"));
        medSpinner->setGeometry(QRect(470, 80, 47, 23));
        label_73 = new QLabel(tab_2);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(360, 290, 101, 16));
        psychanalySpinner = new QSpinBox(tab_2);
        psychanalySpinner->setObjectName(QStringLiteral("psychanalySpinner"));
        psychanalySpinner->setGeometry(QRect(470, 320, 47, 23));
        mRepairSpinner = new QSpinBox(tab_2);
        mRepairSpinner->setObjectName(QStringLiteral("mRepairSpinner"));
        mRepairSpinner->setGeometry(QRect(470, 50, 47, 23));
        naturalSpinner = new QSpinBox(tab_2);
        naturalSpinner->setObjectName(QStringLiteral("naturalSpinner"));
        naturalSpinner->setGeometry(QRect(470, 110, 47, 23));
        swimSpinner = new QSpinBox(tab_2);
        swimSpinner->setObjectName(QStringLiteral("swimSpinner"));
        swimSpinner->setGeometry(QRect(650, 150, 47, 23));
        sleightSpinner = new QSpinBox(tab_2);
        sleightSpinner->setObjectName(QStringLiteral("sleightSpinner"));
        sleightSpinner->setGeometry(QRect(650, 30, 47, 23));
        label_76 = new QLabel(tab_2);
        label_76->setObjectName(QStringLiteral("label_76"));
        label_76->setGeometry(QRect(540, 90, 81, 16));
        label_78 = new QLabel(tab_2);
        label_78->setObjectName(QStringLiteral("label_78"));
        label_78->setGeometry(QRect(540, 60, 81, 16));
        label_80 = new QLabel(tab_2);
        label_80->setObjectName(QStringLiteral("label_80"));
        label_80->setGeometry(QRect(540, 30, 101, 16));
        label_81 = new QLabel(tab_2);
        label_81->setObjectName(QStringLiteral("label_81"));
        label_81->setGeometry(QRect(540, 150, 81, 16));
        throwSpinner = new QSpinBox(tab_2);
        throwSpinner->setObjectName(QStringLiteral("throwSpinner"));
        throwSpinner->setGeometry(QRect(650, 180, 47, 23));
        label_83 = new QLabel(tab_2);
        label_83->setObjectName(QStringLiteral("label_83"));
        label_83->setGeometry(QRect(540, 120, 81, 16));
        label_85 = new QLabel(tab_2);
        label_85->setObjectName(QStringLiteral("label_85"));
        label_85->setGeometry(QRect(540, 180, 81, 16));
        stealthSpinner = new QSpinBox(tab_2);
        stealthSpinner->setObjectName(QStringLiteral("stealthSpinner"));
        stealthSpinner->setGeometry(QRect(650, 90, 47, 23));
        spotSpinner = new QSpinBox(tab_2);
        spotSpinner->setObjectName(QStringLiteral("spotSpinner"));
        spotSpinner->setGeometry(QRect(650, 60, 47, 23));
        survivalSpinner = new QSpinBox(tab_2);
        survivalSpinner->setObjectName(QStringLiteral("survivalSpinner"));
        survivalSpinner->setGeometry(QRect(650, 120, 47, 23));
        label_86 = new QLabel(tab_2);
        label_86->setObjectName(QStringLiteral("label_86"));
        label_86->setGeometry(QRect(540, 210, 81, 16));
        trackSpinner = new QSpinBox(tab_2);
        trackSpinner->setObjectName(QStringLiteral("trackSpinner"));
        trackSpinner->setGeometry(QRect(650, 210, 47, 23));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        descLab = new QLabel(tab_3);
        descLab->setObjectName(QStringLiteral("descLab"));
        descLab->setGeometry(QRect(10, 30, 71, 16));
        descLab_2 = new QLabel(tab_3);
        descLab_2->setObjectName(QStringLiteral("descLab_2"));
        descLab_2->setGeometry(QRect(10, 130, 111, 16));
        descLab_3 = new QLabel(tab_3);
        descLab_3->setObjectName(QStringLiteral("descLab_3"));
        descLab_3->setGeometry(QRect(10, 230, 111, 16));
        descLab_4 = new QLabel(tab_3);
        descLab_4->setObjectName(QStringLiteral("descLab_4"));
        descLab_4->setGeometry(QRect(190, 30, 121, 16));
        descLab_5 = new QLabel(tab_3);
        descLab_5->setObjectName(QStringLiteral("descLab_5"));
        descLab_5->setGeometry(QRect(190, 130, 141, 16));
        descLab_6 = new QLabel(tab_3);
        descLab_6->setObjectName(QStringLiteral("descLab_6"));
        descLab_6->setGeometry(QRect(190, 230, 41, 16));
        descLab_7 = new QLabel(tab_3);
        descLab_7->setObjectName(QStringLiteral("descLab_7"));
        descLab_7->setGeometry(QRect(370, 30, 101, 16));
        descLab_8 = new QLabel(tab_3);
        descLab_8->setObjectName(QStringLiteral("descLab_8"));
        descLab_8->setGeometry(QRect(370, 130, 101, 16));
        descLab_10 = new QLabel(tab_3);
        descLab_10->setObjectName(QStringLiteral("descLab_10"));
        descLab_10->setGeometry(QRect(550, 30, 201, 16));
        descLab_11 = new QLabel(tab_3);
        descLab_11->setObjectName(QStringLiteral("descLab_11"));
        descLab_11->setGeometry(QRect(550, 130, 121, 16));
        descLab_12 = new QLabel(tab_3);
        descLab_12->setObjectName(QStringLiteral("descLab_12"));
        descLab_12->setGeometry(QRect(370, 230, 121, 16));
        descEdit = new QTextEdit(tab_3);
        descEdit->setObjectName(QStringLiteral("descEdit"));
        descEdit->setGeometry(QRect(10, 50, 171, 70));
        beliefEdit = new QTextEdit(tab_3);
        beliefEdit->setObjectName(QStringLiteral("beliefEdit"));
        beliefEdit->setGeometry(QRect(10, 150, 171, 70));
        sigPplEdit = new QTextEdit(tab_3);
        sigPplEdit->setObjectName(QStringLiteral("sigPplEdit"));
        sigPplEdit->setGeometry(QRect(10, 250, 171, 70));
        locEdit = new QTextEdit(tab_3);
        locEdit->setObjectName(QStringLiteral("locEdit"));
        locEdit->setGeometry(QRect(190, 50, 171, 70));
        possEdit = new QTextEdit(tab_3);
        possEdit->setObjectName(QStringLiteral("possEdit"));
        possEdit->setGeometry(QRect(190, 150, 171, 70));
        traitEdit = new QTextEdit(tab_3);
        traitEdit->setObjectName(QStringLiteral("traitEdit"));
        traitEdit->setGeometry(QRect(190, 250, 171, 70));
        injEdit = new QTextEdit(tab_3);
        injEdit->setObjectName(QStringLiteral("injEdit"));
        injEdit->setGeometry(QRect(370, 50, 171, 70));
        fearEdit = new QTextEdit(tab_3);
        fearEdit->setObjectName(QStringLiteral("fearEdit"));
        fearEdit->setGeometry(QRect(370, 150, 171, 70));
        spellEdit = new QTextEdit(tab_3);
        spellEdit->setObjectName(QStringLiteral("spellEdit"));
        spellEdit->setGeometry(QRect(550, 50, 171, 70));
        encounterEdit = new QTextEdit(tab_3);
        encounterEdit->setObjectName(QStringLiteral("encounterEdit"));
        encounterEdit->setGeometry(QRect(550, 150, 171, 70));
        gearEdit = new QTextEdit(tab_3);
        gearEdit->setObjectName(QStringLiteral("gearEdit"));
        gearEdit->setGeometry(QRect(370, 250, 171, 70));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        verticalLayout_2 = new QVBoxLayout(tab_4);
        verticalLayout_2->setSpacing(6);
        verticalLayout_2->setContentsMargins(11, 11, 11, 11);
        verticalLayout_2->setObjectName(QStringLiteral("verticalLayout_2"));
        notesEdit = new QTextEdit(tab_4);
        notesEdit->setObjectName(QStringLiteral("notesEdit"));

        verticalLayout_2->addWidget(notesEdit);

        tabWidget->addTab(tab_4, QString());

        verticalLayout->addWidget(tabWidget);

        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 752, 19));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        label->setText(QApplication::translate("MainWindow", "Name", 0));
        label_2->setText(QApplication::translate("MainWindow", "Age", 0));
        label_3->setText(QApplication::translate("MainWindow", "Player", 0));
        label_4->setText(QApplication::translate("MainWindow", "Occupation", 0));
        label_5->setText(QApplication::translate("MainWindow", "Residence", 0));
        label_6->setText(QApplication::translate("MainWindow", "Birthplace", 0));
        label_7->setText(QApplication::translate("MainWindow", "STR", 0));
        label_8->setText(QApplication::translate("MainWindow", "DEX", 0));
        label_9->setText(QApplication::translate("MainWindow", "INT", 0));
        label_10->setText(QApplication::translate("MainWindow", "CON", 0));
        label_11->setText(QApplication::translate("MainWindow", "APP", 0));
        label_12->setText(QApplication::translate("MainWindow", "POW", 0));
        label_13->setText(QApplication::translate("MainWindow", "SIZ", 0));
        label_14->setText(QApplication::translate("MainWindow", "EDU", 0));
        label_15->setText(QApplication::translate("MainWindow", "HP", 0));
        label_16->setText(QApplication::translate("MainWindow", "Sanity", 0));
        label_17->setText(QApplication::translate("MainWindow", "Magic Points", 0));
        pushButton->setText(QApplication::translate("MainWindow", "Random Character", 0));
        label_18->setText(QApplication::translate("MainWindow", "Luck", 0));
        checkBox->setText(QApplication::translate("MainWindow", "Major Wound", 0));
        label_19->setText(QApplication::translate("MainWindow", "Build", 0));
        label_20->setText(QApplication::translate("MainWindow", "Damage Bonus", 0));
        dmgBonusLab->setText(QApplication::translate("MainWindow", "None", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Info", 0));
        label_35->setText(QApplication::translate("MainWindow", "Accounting", 0));
        label_36->setText(QApplication::translate("MainWindow", "Anthropology", 0));
        label_37->setText(QApplication::translate("MainWindow", "Archaeology", 0));
        label_38->setText(QApplication::translate("MainWindow", "Art/Craft", 0));
        label_39->setText(QApplication::translate("MainWindow", "Charm", 0));
        label_40->setText(QApplication::translate("MainWindow", "Climb", 0));
        label_41->setText(QApplication::translate("MainWindow", "Credit Rating", 0));
        label_42->setText(QApplication::translate("MainWindow", "Cthulhu Mythos", 0));
        label_43->setText(QApplication::translate("MainWindow", "Disguise", 0));
        label_44->setText(QApplication::translate("MainWindow", "Dodge", 0));
        label_45->setText(QApplication::translate("MainWindow", "Drive Auto", 0));
        label_46->setText(QApplication::translate("MainWindow", "Elec Repair", 0));
        label_47->setText(QApplication::translate("MainWindow", "Appraise", 0));
        label_48->setText(QApplication::translate("MainWindow", "Fight(Brawl)", 0));
        label_49->setText(QApplication::translate("MainWindow", "Language(Other)", 0));
        label_50->setText(QApplication::translate("MainWindow", "Handgun", 0));
        label_51->setText(QApplication::translate("MainWindow", "Rifle/Shotgun", 0));
        label_52->setText(QApplication::translate("MainWindow", "Jump", 0));
        label_53->setText(QApplication::translate("MainWindow", "Fast Talk", 0));
        label_54->setText(QApplication::translate("MainWindow", "History", 0));
        label_55->setText(QApplication::translate("MainWindow", "Listen", 0));
        label_56->setText(QApplication::translate("MainWindow", "Intimidate", 0));
        label_57->setText(QApplication::translate("MainWindow", "Language(Own)", 0));
        label_58->setText(QApplication::translate("MainWindow", "First Aid", 0));
        label_59->setText(QApplication::translate("MainWindow", "Library Use", 0));
        label_60->setText(QApplication::translate("MainWindow", "Law", 0));
        label_61->setText(QApplication::translate("MainWindow", "Science", 0));
        label_62->setText(QApplication::translate("MainWindow", "Psychoanalysis", 0));
        label_63->setText(QApplication::translate("MainWindow", "Medicine", 0));
        label_64->setText(QApplication::translate("MainWindow", "Pilot", 0));
        label_65->setText(QApplication::translate("MainWindow", "Mech. Repair", 0));
        label_66->setText(QApplication::translate("MainWindow", "Persuade", 0));
        label_67->setText(QApplication::translate("MainWindow", "Locksmith", 0));
        label_68->setText(QApplication::translate("MainWindow", "Navigate", 0));
        label_69->setText(QApplication::translate("MainWindow", "Op. Hv. Machine", 0));
        label_70->setText(QApplication::translate("MainWindow", "Natural World", 0));
        label_71->setText(QApplication::translate("MainWindow", "Ride", 0));
        label_72->setText(QApplication::translate("MainWindow", "Occult", 0));
        label_73->setText(QApplication::translate("MainWindow", "Psychology", 0));
        label_76->setText(QApplication::translate("MainWindow", "Stealth", 0));
        label_78->setText(QApplication::translate("MainWindow", "Spot Hidden", 0));
        label_80->setText(QApplication::translate("MainWindow", "Sleight of Hand", 0));
        label_81->setText(QApplication::translate("MainWindow", "Swim", 0));
        label_83->setText(QApplication::translate("MainWindow", "Survival", 0));
        label_85->setText(QApplication::translate("MainWindow", "Throw", 0));
        label_86->setText(QApplication::translate("MainWindow", "Track", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Skills", 0));
        descLab->setText(QApplication::translate("MainWindow", "Description", 0));
        descLab_2->setText(QApplication::translate("MainWindow", "Ideologies/Beliefs", 0));
        descLab_3->setText(QApplication::translate("MainWindow", "Significant People", 0));
        descLab_4->setText(QApplication::translate("MainWindow", "Meaninful Locations", 0));
        descLab_5->setText(QApplication::translate("MainWindow", "Treasured Possessions", 0));
        descLab_6->setText(QApplication::translate("MainWindow", "Traits", 0));
        descLab_7->setText(QApplication::translate("MainWindow", "Injuries & Scars", 0));
        descLab_8->setText(QApplication::translate("MainWindow", "Phobia & Fears", 0));
        descLab_10->setText(QApplication::translate("MainWindow", "Tomes, Spells & Artifacts", 0));
        descLab_11->setText(QApplication::translate("MainWindow", "Strange Encounters", 0));
        descLab_12->setText(QApplication::translate("MainWindow", "Gear & Possessions", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "Background", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "Notes", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
